test "Type error"
{
    try {
        12 + '2'
        assert(got: false)
    } catch {
        InvalidType() => assert(got: true)
    }
}